apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue-deployment
  namespace: distribuidos
  labels:
   app: microservices-example
spec:
  replicas: 2
  selector:
    matchLabels:
         app: microservices-example
         type: redis-queue
  template:
    metadata:
      labels:
        app: microservices-example
        type: redis-queue
    spec:
     containers:
     - name: redis-queue
       image: redis/redis-stack-server:latest
       ports:
        - containerPort: 6379
